globals:
  seed: 5713
  debug: False
  num_epochs: 35
  num_feats: 20

path:
  dir_train: '../../data_ignore/input/train/'
  dir_test: '../../data_ignore/input/test/'
  path_train_tp: '../../data_ignore/input/train_tp.csv'
  path_sample_submission: '../../data_ignore/input/sample_submission.csv'
  dir_save: '../../data/exp/'
  dir_save_ignore: '../../data_ignore/exp/'

dataset:
  name: SpectrogramDatasetWithHPSS
  params:
    period: 5
    shift_duration: 4
    img_size: 224
  melspec_params:
    n_mels: 128
    # n_mels: 256
    fmin: 90
    fmax: 14000

loader:
  train:
    batch_size: 512
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 512
    shuffle: False
    num_workers: 4
  test:
    batch_size: 512
    shuffle: False
    num_workers: 4
    

split:
  seed: 5713
  n_fold: 5
  # n_fold: 2
 
model:
  name: ResNet18
  params:
    pretrained: True
    n_classes: 24

loss:
  name: MSELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.1
    patience: 3



